=== thevlad0/XML-Semantic-Web/schema.xsd
<?xml version="1.0"?>
<xs:schema 
    xmlns:xs="http://www.w3.org/2001/XMLSchema"
    elementFormDefault="qualified"
>

<!-- ROOT ELEMENT DEFINITION -->
<xs:element name="catalog">
    <xs:complexType>
        <xs:sequence>
            <xs:element name="brands" type="brandsSelectorType"/>
            <xs:element name="products" type="productsSelectorType"/>
        </xs:sequence>
    </xs:complexType>

    <!-- Key definitions -->
    <xs:key name="brandKey">
        <xs:selector xpath="brands/brand"/>
        <xs:field xpath="."/>
    </xs:key>

    <!-- Keyref definitions -->
    <xs:keyref name="brandRef" refer="brandKey">
        <xs:selector xpath="products/product"/>
        <xs:field xpath="brand"/>
    </xs:keyref>

</xs:element>

<!-- MAIN TYPE DEFINITIONS -->

<!-- Base product type definition -->
<xs:complexType name="productType">
    <xs:sequence>
        <xs:element name="colors" type="colorsSelectorType" minOccurs="0"/>

        <xs:element name="image" type="imageType" minOccurs="0"/>
        <xs:element name="name" type="xs:string" minOccurs="0"/>
        <xs:element name="brand" type="xs:string" minOccurs="0"/>
        <xs:element name="model" type="xs:string" minOccurs="0"/>
        <xs:element name="price" type="priceType" minOccurs="0"/>
    </xs:sequence>
</xs:complexType>

<!-- Specific product type definitions -->

<xs:complexType name="keyboardType">
    <xs:complexContent>
        <xs:extension base="productType">
            <xs:sequence>
                <xs:element name="type">
                    <xs:simpleType>
                        <xs:restriction base="xs:string">
                            <xs:enumeration value="mechanical"/>
                            <xs:enumeration value="membrane"/>
                        </xs:restriction>
                    </xs:simpleType>
                </xs:element>
                <xs:element name="full-sized" type="xs:boolean"/>
                <xs:element name="connectivity" type="connectivityType"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="mouseType">
    <xs:complexContent>
        <xs:extension base="productType">
            <xs:sequence>
                <xs:element name="dpi" type="xs:positiveInteger"/>
                <xs:element name="buttons" type="xs:positiveInteger"/>
                <xs:element name="connectivity" type="connectivityType"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="displayType">
    <xs:complexContent>
        <xs:extension base="productType">
            <xs:sequence>
                <xs:element name="resolution" type="xs:string"/>
                <xs:element name="refreshRate" type="xs:positiveInteger"/>
                <xs:element name="diagonalSize" type="xs:decimal"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="laptopType">
    <xs:complexContent>
        <xs:extension base="productType">
            <xs:sequence>
                <xs:element name="os" type="osType"/>
                <xs:element name="processor" type="xs:string"/>
                <xs:element name="ram" type="xs:positiveInteger"/>
                <xs:element name="storage" type="storageType"/>
                <xs:element name="mouse" type="mouseType" minOccurs="0"/>
                <xs:element name="keyboard" type="keyboardType" minOccurs="0"/>
                <xs:element name="display" type="displayType" minOccurs="0"/>
            </xs:sequence>
        </xs:extension>
    </xs:complexContent>
</xs:complexType>

<xs:complexType name="desktopType">
    <xs:complexContent>
        <xs:extension base="laptopType"/>
    </xs:complexContent>
</xs:complexType>

<!-- UTILITY TYPE DEFINITIONS -->

<!-- Readability type definitions -->
<xs:complexType name="brandsSelectorType">
    <xs:sequence>
        <xs:element name="brand" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="colorsSelectorType">
    <xs:sequence>
        <xs:element name="color" type="xs:string" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<xs:complexType name="productsSelectorType">
    <xs:sequence>
        <xs:element name="product" type="productType" maxOccurs="unbounded"/>
    </xs:sequence>
</xs:complexType>

<!-- Content simplification type definitions -->
<xs:simpleType name="osType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="Windows"/>
        <xs:enumeration value="MacOS"/>
        <xs:enumeration value="Linux"/>
        <xs:enumeration value="none"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="storageType">
    <xs:simpleContent>
        <xs:extension base="positiveValueRestriction">
            <xs:attribute name="unit" type="storageUnitType" use="required"/>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="storageUnitType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="GB"/>
        <xs:enumeration value="TB"/>
    </xs:restriction>
</xs:simpleType>

<xs:simpleType name="connectivityType">
    <xs:restriction base="xs:string">
        <xs:enumeration value="wired"/>
        <xs:enumeration value="wireless"/>
        <xs:enumeration value="bluetooth"/>
        <xs:enumeration value="embedded"/>
    </xs:restriction>
</xs:simpleType>

<xs:complexType name="imageType">
    <xs:attribute name="src" type="xs:anyURI" use="required"/>
</xs:complexType>

<xs:complexType name="priceType">
    <xs:simpleContent>
        <xs:extension base="positiveValueRestriction">
            <xs:attribute name="currency" use="required">
                <xs:simpleType>
                    <xs:restriction base="xs:string">
                        <xs:enumeration value="BGN"/>
                        <xs:enumeration value="EUR"/>
                    </xs:restriction>
                </xs:simpleType>
            </xs:attribute>
        </xs:extension>
    </xs:simpleContent>
</xs:complexType>

<xs:simpleType name="positiveValueRestriction">
    <xs:restriction base="xs:decimal">
        <xs:minInclusive value="0"/>
    </xs:restriction>
</xs:simpleType>

</xs:schema>

=== thevlad0/XML-Semantic-Web/source.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet href="translator.xsl" type="text/xsl"?>

<catalog xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:noNamespaceSchemaLocation="schema.xsd"
>
    <brands>
        <brand>Logitech</brand>
        <brand>Microsoft</brand>
        <brand>Dell</brand>
        <brand>Apple</brand>
    </brands>

    <products>
        <product xsi:type="keyboardType">
            <colors>
                <color>black</color>
                <color>white</color>
            </colors>

            <image src="images/keyboard1.jpg"/>
            <name>Logitech G413</name>
            <brand>Logitech</brand>
            <model>G413</model>
            <price currency="BGN">118.99</price>
            
            <type>mechanical</type>
            <full-sized>true</full-sized>
            <connectivity>wired</connectivity>
        </product>

        <product xsi:type="keyboardType">
            <colors>
                <color>black</color>
            </colors>

            <image src="images/keyboard2.jpg"/>
            <name>Microsoft Ergonomic Keyboard</name>
            <brand>Microsoft</brand>
            <model>LXM-00004</model>
            <price currency="EUR">189.99</price>
            
            <type>membrane</type>
            <full-sized>false</full-sized>
            <connectivity>wireless</connectivity>
        </product>

        <product xsi:type="mouseType">
            <colors>
                <color>black</color>
                <color>white</color>
            </colors>

            <image src="images/mouse1.jpeg"/>
            <name>Apple Magic Mouse</name>
            <brand>Apple</brand>
            <model>Magic Mouse</model>
            <price currency="EUR">79.99</price>
            
            <dpi>1300</dpi>
            <buttons>1</buttons>
            <connectivity>bluetooth</connectivity>
        </product>

        <product xsi:type="laptopType">
            <image src="images/laptop1.jpg"/>
            <name>Apple MacBook Pro 14 (M3)</name>
            <brand>Apple</brand>
            <model>MacBook Pro 14 M3</model>
            <price currency="BGN">3799.99</price>
            
            <os>MacOS</os>
            <processor>Apple M3</processor>
            <ram>8</ram>
            <storage unit="GB">512</storage>

            <keyboard>
                <type>membrane</type>
                <full-sized>true</full-sized>
                <connectivity>embedded</connectivity>
            </keyboard>

            <display>
                <resolution>3024x1964</resolution>
                <refreshRate>60</refreshRate>
                <diagonalSize>14</diagonalSize>
            </display>
        </product>

        <product xsi:type="laptopType">
            <image src="images/laptop2.avif"/>
            <name>Dell XPS 16</name>
            <brand>Dell</brand>
            <model>XPS 16</model>
            <price>6627.99</price>
            
            <os>Windows</os>
            <processor>Intel Core Ultra 7</processor>
            <ram>16</ram>
            <storage unit="TB">2</storage>

            <keyboard>
                <type>membrane</type>
                <full-sized>false</full-sized>
                <connectivity>embedded</connectivity>
            </keyboard>

            <display>
                <resolution>1920x1080</resolution>
                <refreshRate>60</refreshRate>
                <diagonalSize>13</diagonalSize>
            </display>
        </product>

        <product xsi:type="laptopType">
            <image src="images/laptop3.jpg"/>
            <name>Microsoft Surface Laptop 4</name>
            <brand>Microsoft</brand>
            <model>Surface Laptop 4</model>
            <price currency="EUR">1199.99</price>
            
            <os>Windows</os>
            <processor>Intel Core i5</processor>
            <ram>8</ram>
            <storage unit="GB">256</storage>

            <keyboard>
                <type>membrane</type>
                <full-sized>true</full-sized>
                <connectivity>embedded</connectivity>
            </keyboard>

            <display>
                <resolution>2256x1504</resolution>
                <refreshRate>60</refreshRate>
                <diagonalSize>13.5</diagonalSize>
            </display>
        </product>

        <product xsi:type="desktopType">
            <image src="images/desktop1.jpg"/>
            <name>Apple Mac Mini</name>
            <brand>Apple</brand>
            <model>Mac Mini</model>
            <price currency="EUR">649.99</price>
            
            <os>MacOS</os>
            <processor>Apple M1</processor>
            <ram>8</ram>
            <storage unit="GB">512</storage>
        </product>

        <product xsi:type="displayType">
            <colors>
                <color>black</color>
            </colors>

            <image src="images/monitor1.jpg"/>
            <name>Dell UltraSharp U2415</name>
            <brand>Dell</brand>
            <model>UltraSharp U2415</model>
            <price currency="BGN">249.99</price>

            <resolution>1920x1200</resolution>
            <refreshRate>60</refreshRate>
            <diagonalSize>24</diagonalSize>
        </product>

        <product xsi:type="displayType">
            <image src="images/monitor2.avif"/>
            <name>Dell S2721DGF</name>
            <brand>Dell</brand>
            <model>S2721DGF</model>
            <price currency="BGN">799.99</price>

            <resolution>2560x1440</resolution>
            <refreshRate>165</refreshRate>
            <diagonalSize>27</diagonalSize>
        </product>

    </products>

</catalog>
